services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: workq_user
      POSTGRES_PASSWORD: workq_password

  pulsar:
    image: apachepulsar/pulsar:latest
    ports:
      - 6650:6650
    command: >
      /pulsar/bin/pulsar standalone
